package com.pixel.launcher.core

// GENERATED by tools/gen_iconpack.py - do not edit by hand.
// Edit the grids in that script and re-run it instead.

internal object PixelIconArt {

    val bank = PixelIcon(
        bg = 0xFF00897B.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " ########## ",
            " ##      ## ",
            " ##      ## ",
            " ##    #### ",
            " ##    # ## ",
            " ##    #### ",
            " ########## ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val calculator = PixelIcon(
        bg = 0xFF3C4043.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            " ########## ",
            " #        # ",
            " #  ####  # ",
            " #        # ",
            " # ## ##  # ",
            " #        # ",
            " # ## ##  # ",
            " #        # ",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val calendar = PixelIcon(
        bg = 0xFF1A73E8.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "  ##    ##  ",
            " ########## ",
            " ########## ",
            " #        # ",
            " # ## ##  # ",
            " #        # ",
            " # ## ##  # ",
            " #        # ",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val camera = PixelIcon(
        bg = 0xFF3C4043.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "     ###    ",
            "  ########  ",
            " ########## ",
            " ###    ### ",
            " ##  ##  ## ",
            " ##  ##  ## ",
            " ###    ### ",
            " ########## ",
            "  ########  ",
            "            ",
            "            ",
        ),
    )

    val cart = PixelIcon(
        bg = 0xFFF4511E.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            " ##         ",
            " ######     ",
            " #    ##    ",
            " #     ##   ",
            " #    ###   ",
            " ######     ",
            "   ##  ##   ",
            "            ",
            "  ##    ##  ",
            "            ",
            "            ",
        ),
    )

    val chat = PixelIcon(
        bg = 0xFF075E54.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ########  ",
            " ##      ## ",
            " ##  ##  ## ",
            " ##  ##  ## ",
            " ##      ## ",
            "  ########  ",
            "   #######  ",
            "  ###       ",
            "            ",
            "            ",
        ),
    )

    val chrome = PixelIcon(
        bg = 0xFF1A73E8.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFFBBC05.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ##    ##  ",
            " ##  ##  ## ",
            " ## #  # ## ",
            " ########## ",
            " ## #  # ## ",
            " ##  ##  ## ",
            "  ##    ##  ",
            "   ######   ",
            "            ",
            "            ",
        ),
    )

    val clock = PixelIcon(
        bg = 0xFF202124.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ##    ##  ",
            " ##  #   ## ",
            " ##  #   ## ",
            " ##  ###  # ",
            " ##      ## ",
            " ##      ## ",
            "  ##    ##  ",
            "   ######   ",
            "            ",
            "            ",
        ),
    )

    val contacts = PixelIcon(
        bg = 0xFF1E8E3E.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   #####    ",
            "  ##   ##   ",
            "  ##   ##   ",
            "   #####    ",
            "    ###     ",
            "     ###    ",
            "      ###   ",
            "      ##  ##",
            "       ## ##",
            "        ####",
            "            ",
        ),
    )

    val discord = PixelIcon(
        bg = 0xFF5865F2.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            "  ########  ",
            " ########## ",
            " # ##   # # ",
            " ####  ## # ",
            " # ##   # # ",
            " ########## ",
            "  ##    ##  ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val facebook = PixelIcon(
        bg = 0xFF1877F2.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            " ########## ",
            " ##      ## ",
            " #   ##   # ",
            " #  ####  # ",
            " #  ####  # ",
            " #   ##   # ",
            " ##      ## ",
            " ####   ### ",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val files = PixelIcon(
        bg = 0xFFFBBC05.toInt(),
        fg = 0xFF12141A.toInt(),
        accent = 0xFF12141A.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " ####       ",
            " ########## ",
            " ##      ## ",
            " ##      ## ",
            " ##      ## ",
            " ##      ## ",
            " ########## ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val firefox = PixelIcon(
        bg = 0xFFFF7139.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ##    ##  ",
            " ##  ##  ## ",
            " ## #  # ## ",
            " ########## ",
            " ## #  # ## ",
            " ##  ##  ## ",
            "  ##    ##  ",
            "   ######   ",
            "            ",
            "            ",
        ),
    )

    val folder = PixelIcon(
        bg = 0xFFFBBC05.toInt(),
        fg = 0xFF12141A.toInt(),
        accent = 0xFF12141A.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " ####       ",
            " ########## ",
            " ##      ## ",
            " ##      ## ",
            " ##      ## ",
            " ##      ## ",
            " ########## ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val gallery = PixelIcon(
        bg = 0xFF4285F4.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFFBBC05.toInt(),
        rows = listOf(
            "            ",
            " ########## ",
            " #        # ",
            " #  ++    # ",
            " #        # ",
            " #    ##  # ",
            " #   #### # ",
            " #  ##### # ",
            " ######### #",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val gamepad = PixelIcon(
        bg = 0xFF5865F2.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            "  ########  ",
            " ########## ",
            " # ##   # # ",
            " ####  ## # ",
            " # ##   # # ",
            " ########## ",
            "  ##    ##  ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val games = PixelIcon(
        bg = 0xFF7B1FA2.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            "  ########  ",
            " ########## ",
            " # ##   # # ",
            " ####  ## # ",
            " # ##   # # ",
            " ########## ",
            "  ##    ##  ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val globe = PixelIcon(
        bg = 0xFF1A73E8.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ##    ##  ",
            " ##  ##  ## ",
            " ## #  # ## ",
            " ########## ",
            " ## #  # ## ",
            " ##  ##  ## ",
            "  ##    ##  ",
            "   ######   ",
            "            ",
            "            ",
        ),
    )

    val gmail = PixelIcon(
        bg = 0xFFD93025.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " ########## ",
            " ##      ## ",
            " # ##  ## # ",
            " #   ##   # ",
            " #  #  #  # ",
            " ## #  # ## ",
            " ########## ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val instagram = PixelIcon(
        bg = 0xFFC13584.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            " ########## ",
            " ##      ## ",
            " #   ##   # ",
            " #  ####  # ",
            " #  ####  # ",
            " #   ##   # ",
            " ##      ## ",
            " ####   ### ",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val mail = PixelIcon(
        bg = 0xFFD93025.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " ########## ",
            " ##      ## ",
            " # ##  ## # ",
            " #   ##   # ",
            " #  #  #  # ",
            " ## #  # ## ",
            " ########## ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val maps = PixelIcon(
        bg = 0xFF34A853.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ########  ",
            " ###    ### ",
            " ##  ##  ## ",
            " ##  ##  ## ",
            " ###    ### ",
            "  ########  ",
            "   ######   ",
            "    ####    ",
            "     ##     ",
            "            ",
        ),
    )

    val message = PixelIcon(
        bg = 0xFF1A73E8.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "  ########  ",
            " ########## ",
            " ########## ",
            " ## ## ## # ",
            " ########## ",
            " ########## ",
            " ########## ",
            "  ######### ",
            "  ###       ",
            "  #         ",
            "            ",
        ),
    )

    val music = PixelIcon(
        bg = 0xFFEA4335.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "       #### ",
            "       #### ",
            "       ##   ",
            "       ##   ",
            "       ##   ",
            "  ###  ##   ",
            " ##### ##   ",
            " #####      ",
            "  ###       ",
            "            ",
            "            ",
        ),
    )

    val netflix = PixelIcon(
        bg = 0xFF12141A.toInt(),
        fg = 0xFFE50914.toInt(),
        accent = 0xFFE50914.toInt(),
        rows = listOf(
            "            ",
            "  ########  ",
            " ########## ",
            " ###    ### ",
            " ##  #   ## ",
            " ##  ###  # ",
            " ##  #   ## ",
            " ###    ### ",
            " ########## ",
            "  ########  ",
            "            ",
            "            ",
        ),
    )

    val note = PixelIcon(
        bg = 0xFFEA4335.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "       #### ",
            "       #### ",
            "       ##   ",
            "       ##   ",
            "       ##   ",
            "  ###  ##   ",
            " ##### ##   ",
            " #####      ",
            "  ###       ",
            "            ",
            "            ",
        ),
    )

    val phone = PixelIcon(
        bg = 0xFF1E8E3E.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   #####    ",
            "  ##   ##   ",
            "  ##   ##   ",
            "   #####    ",
            "    ###     ",
            "     ###    ",
            "      ###   ",
            "      ##  ##",
            "       ## ##",
            "        ####",
            "            ",
        ),
    )

    val photos = PixelIcon(
        bg = 0xFF4285F4.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFFBBC05.toInt(),
        rows = listOf(
            "            ",
            " ########## ",
            " #        # ",
            " #  ++    # ",
            " #        # ",
            " #    ##  # ",
            " #   #### # ",
            " #  ##### # ",
            " ######### #",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val pin = PixelIcon(
        bg = 0xFF34A853.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ########  ",
            " ###    ### ",
            " ##  ##  ## ",
            " ##  ##  ## ",
            " ###    ### ",
            "  ########  ",
            "   ######   ",
            "    ####    ",
            "     ##     ",
            "            ",
        ),
    )

    val plane = PixelIcon(
        bg = 0xFF229ED9.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "         ## ",
            "       #### ",
            "     ###### ",
            "   ######   ",
            " ######     ",
            "   ####     ",
            "    ###     ",
            "     ##     ",
            "      #     ",
            "            ",
            "            ",
        ),
    )

    val play = PixelIcon(
        bg = 0xFFCC0000.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "  ########  ",
            " ########## ",
            " ###    ### ",
            " ##  #   ## ",
            " ##  ###  # ",
            " ##  #   ## ",
            " ###    ### ",
            " ########## ",
            "  ########  ",
            "            ",
            "            ",
        ),
    )

    val player = PixelIcon(
        bg = 0xFF9334E6.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " #######    ",
            " ##   ##  # ",
            " ##  # #### ",
            " ##   # ### ",
            " ##  # #### ",
            " ##   ##  # ",
            " #######    ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val playstore = PixelIcon(
        bg = 0xFF34A853.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ##       ",
            "   ###      ",
            "   ####     ",
            "   #####    ",
            "   ######   ",
            "   #####    ",
            "   ####     ",
            "   ###      ",
            "   ##       ",
            "            ",
            "            ",
        ),
    )

    val shop = PixelIcon(
        bg = 0xFFF4511E.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            " ##         ",
            " ######     ",
            " #    ##    ",
            " #     ##   ",
            " #    ###   ",
            " ######     ",
            "   ##  ##   ",
            "            ",
            "  ##    ##  ",
            "            ",
            "            ",
        ),
    )

    val sms = PixelIcon(
        bg = 0xFF1A73E8.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "  ########  ",
            " ########## ",
            " ########## ",
            " ## ## ## # ",
            " ########## ",
            " ########## ",
            " ########## ",
            "  ######### ",
            "  ###       ",
            "  #         ",
            "            ",
        ),
    )

    val spotify = PixelIcon(
        bg = 0xFF1DB954.toInt(),
        fg = 0xFF12141A.toInt(),
        accent = 0xFF12141A.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ########  ",
            " ###    ### ",
            " ## #### ## ",
            " ##      ## ",
            " ## #### ## ",
            " ###    ### ",
            "  ########  ",
            "   ######   ",
            "            ",
            "            ",
        ),
    )

    val square = PixelIcon(
        bg = 0xFFC13584.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            " ########## ",
            " ##      ## ",
            " #   ##   # ",
            " #  ####  # ",
            " #  ####  # ",
            " #   ##   # ",
            " ##      ## ",
            " ####   ### ",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val store = PixelIcon(
        bg = 0xFF34A853.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "   ##       ",
            "   ###      ",
            "   ####     ",
            "   #####    ",
            "   ######   ",
            "   #####    ",
            "   ####     ",
            "   ###      ",
            "   ##       ",
            "            ",
            "            ",
        ),
    )

    val telegram = PixelIcon(
        bg = 0xFF229ED9.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "         ## ",
            "       #### ",
            "     ###### ",
            "   ######   ",
            " ######     ",
            "   ####     ",
            "    ###     ",
            "     ##     ",
            "      #     ",
            "            ",
            "            ",
        ),
    )

    val tiktok = PixelIcon(
        bg = 0xFF12141A.toInt(),
        fg = 0xFF25F4EE.toInt(),
        accent = 0xFFFE2C55.toInt(),
        rows = listOf(
            "            ",
            "       #### ",
            "       #### ",
            "       ##   ",
            "       ##   ",
            "       ##   ",
            "  ###  ##   ",
            " ##### ##   ",
            " #####      ",
            "  ###       ",
            "            ",
            "            ",
        ),
    )

    val twitter = PixelIcon(
        bg = 0xFF12141A.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            " ########## ",
            " ##      ## ",
            " #   ##   # ",
            " #  ####  # ",
            " #  ####  # ",
            " #   ##   # ",
            " ##      ## ",
            " ####   ### ",
            " ########## ",
            "            ",
            "            ",
        ),
    )

    val video = PixelIcon(
        bg = 0xFF9334E6.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " #######    ",
            " ##   ##  # ",
            " ##  # #### ",
            " ##   # ### ",
            " ##  # #### ",
            " ##   ##  # ",
            " #######    ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val wallet = PixelIcon(
        bg = 0xFF00897B.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "            ",
            " ########## ",
            " ##      ## ",
            " ##      ## ",
            " ##    #### ",
            " ##    # ## ",
            " ##    #### ",
            " ########## ",
            "            ",
            "            ",
            "            ",
        ),
    )

    val wave = PixelIcon(
        bg = 0xFF1DB954.toInt(),
        fg = 0xFF12141A.toInt(),
        accent = 0xFF12141A.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ########  ",
            " ###    ### ",
            " ## #### ## ",
            " ##      ## ",
            " ## #### ## ",
            " ###    ### ",
            "  ########  ",
            "   ######   ",
            "            ",
            "            ",
        ),
    )

    val whatsapp = PixelIcon(
        bg = 0xFF075E54.toInt(),
        fg = 0xFF25D366.toInt(),
        accent = 0xFF25D366.toInt(),
        rows = listOf(
            "            ",
            "   ######   ",
            "  ########  ",
            " ##      ## ",
            " ##  ##  ## ",
            " ##  ##  ## ",
            " ##      ## ",
            "  ########  ",
            "   #######  ",
            "  ###       ",
            "            ",
            "            ",
        ),
    )

    val youtube = PixelIcon(
        bg = 0xFFCC0000.toInt(),
        fg = 0xFFF4F4F4.toInt(),
        accent = 0xFFF4F4F4.toInt(),
        rows = listOf(
            "            ",
            "  ########  ",
            " ########## ",
            " ###    ### ",
            " ##  #   ## ",
            " ##  ###  # ",
            " ##  #   ## ",
            " ###    ### ",
            " ########## ",
            "  ########  ",
            "            ",
            "            ",
        ),
    )

}
